version: '3.9'

services:
  mysql:
    image: mysql:8.4.0-oraclelinux9
    container_name: mysql_database
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306

  phpMyAdmin:
    image: phpmyadmin:5.2.1-apache
    container_name: phpMyAdmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
